# Generated by Django 3.0.5 on 2021-07-13 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('user', 'User role'), ('moderator', 'Moderator role'), ('admin', 'Admin role')], default=('user', 'User role'), max_length=50),
        ),
    ]
